name: Python Script Runner

# Hansı hadisə baş verəndə işə düşsün?
on:
  push:
    branches: [ "main" ] # "main" budağına commit gələndə
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # GitHub-un təmin etdiyi virtual maşın

    steps:
    - name: Kodu kopyala
      uses: actions/checkout@v4 # Kodunuzu virtual maşına yükləyir

    - name: Python-u quraşdır
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # İstədiyiniz versiyanı yaza bilərsiniz

    - name: Kitabxanaları yüklə
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Python faylını işlət
      run: python generate_metadata.py  # Bura işlətmək istədiyiniz faylın adını yazın
